<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>bisse_tutorial – PhylogeogRaphy Workshop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../img/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../css/styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-house" role="img">
</i> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../monday.html"> <i class="bi bi-pie-chart" role="img">
</i> 
<span class="menu-text">Day 1: Discrete trait analysis I in R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../wednesday.html"> <i class="bi bi-map" role="img">
</i> 
<span class="menu-text">Day 2: Discrete trait analysis II in R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../thursday.html"> <i class="bi bi-activity" role="img">
</i> 
<span class="menu-text">Day 3: Phylodynamics I in R and BEAST2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../friday.html"> <i class="bi bi-tree" role="img">
</i> 
<span class="menu-text">Day 4: Phylodynamics II in BEAST2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> <i class="bi bi-space-shuttle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/alexbeams/phylogeography_workshop" title="" class="quarto-navigation-tool px-1" aria-label="GitHub organization" target="_blank"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="using-binary-state-speciation-and-extinction-bisse-models-to-understand-trait-change-in-the-hymenoptera" class="level1">
<h1>Using Binary State Speciation and Extinction (BiSSE) models to understand trait change in the Hymenoptera</h1>
<p>In Day 1, we modeled changes in discrete traits and geographic locations using Markov models defined on phylogenetic trees. We’re following this theme, but are now focusing on situations where traits/geography interact with the diversification process.</p>
<p>So far, we have been treating the trees as given without asking how they are created (by some biologist, presumably). If the traits we are interested in do not influence diversification, extinction/death, or the probability we observe a particular lineage, then the standard Markov models on trees seem sufficient. If, on the other hand, traits do influence the process creating the phylogenetic relationships we observe, we would like to estimate these effects. In addition to learning something new about the evolutionary process, this will allow us to control for these effects when carrying out ancestral state reconstructions.</p>
<p>The main package that is new to us today is “diversitree”. This includes functions to make and fit BiSSE models (and extensions that include multiple states, etc).</p>
<p>Let’s load in all of the packages we need:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(diversitree)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggtree)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ape)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(phytools)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We’re loading in ape and phytools so that we can compare results from our earlier methods with these newer ones.</p>
<p>An important point: diversitree was designed for applications in macroevolution, where phylogenetic trees are predominantly ultrametric. This means that all tips of the phylogenies occur at the same point in time. In macroevolution, where researchers are interested to understand evolutionary forces shaping organisms we observe today, most phylogenies will be ultrametric. In some instances, people use fossil data to have tips in phylogenies occurring in the very distant past so that trees are not ultrametric, but this is not something we will do today. (Fossil data can also be used to represent nodes of phylogenetic trees – but this only makes sense if species represented in fossils are ancestors of present-day organisms, which is not always the case.)</p>
<p>Ultrametric trees are not common in infectious disease epidemiology. However, BiSSE and its variants are conceptually related to models like the Multi-type birth-death model, which is often used to study infectious diseases and is available in BEAST2. An understanding of these macroevolutionary models will help us work with more complicated models in infectious disease analyses.</p>
<section id="trait-change-in-the-hymenoptera" class="level2">
<h2 class="anchored" data-anchor-id="trait-change-in-the-hymenoptera">Trait change in the Hymenoptera</h2>
<p>Let’s start by reading in an example phylogenetic tree for the <em>Hymenoptera</em>. This an order of insects that includes wasps, bees, and ants. These data are publicly available, and were analyzed in</p>
<p><strong>Blaimer, B.B., Santos, B.F., Cruaud, A. et al.&nbsp;Key innovations and the diversification of Hymenoptera. Nat Commun 14, 1212 (2023). https://doi.org/10.1038/s41467-023-36868-4.</strong></p>
<p>There are several different datasets with trait information associated with this phylogeny. One of these is carnivory (a binary trait for whether or not a particular species eats other insects).</p>
<p>Let’s read in the tree and the associated carnivory data. Due to some slight mismatch between species names in the tree and in the carnivory dataset, I have a handful of additional commands that manually rename species to be consistent (mostly by moving underscores and spaces):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tree <span class="ot">&lt;-</span> <span class="fu">read.tree</span>(<span class="st">"hymenoptera_data/HYMtopA_bamm_hisse.phy"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>carndat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'hymenoptera_data/Carnivory.csv'</span>, <span class="at">header=</span><span class="cn">FALSE</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>xcarn <span class="ot">&lt;-</span> carndat[,<span class="dv">2</span>]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(xcarn) <span class="ot">&lt;-</span> carndat[,<span class="dv">1</span>]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># there are some name issues we have to sort out</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>znms <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(xcarn), tree<span class="sc">$</span>tip.label)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>wnms <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(tree<span class="sc">$</span>tip.label, <span class="fu">names</span>(xcarn))</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># It's fairly obvious what needs to be fixed - let's just do this manually:</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>badinds <span class="ot">&lt;-</span> <span class="fu">sapply</span>(znms, <span class="cf">function</span>(x) <span class="fu">which</span>(<span class="fu">names</span>(xcarn)<span class="sc">==</span>x))</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># reorder wnms to match znms</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>wwnms <span class="ot">&lt;-</span> wnms[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">9</span>,<span class="dv">10</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">11</span>,<span class="dv">8</span>,<span class="dv">2</span>,<span class="dv">7</span>)]</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># visually check that we have these in the correct order:</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(znms, wwnms)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]                                  [,2]                          
znms  "Chalcimerus _borceai_JRAS01317_0301" "Chyphotes_mellipes_HPG7"     
wwnms "Chalcimerus_borceai_JRAS01317_0301"  "CHYP_Chyphotes_mellipes_HPG7"
      [,3]                      [,4]                       
znms  "Chyphotes_sp_EX553"      "Hidryta_fusiventris_CO492"
wwnms "CHYP_Chyphotes_sp_EX553" "Hidryta_fusiventris_C0492"
      [,5]                    [,6]                            
znms  "Isolia_sp_OSUC698060"  "Janzenella_innupta_OSUC264384" 
wwnms "Isolia_sp_OSUC_698060" "Janzenella_innupta_OSUC_264384"
      [,7]                             [,8]                   
znms  "Phaeogenes_ss_sp_BS_UCE_Ich212" "Pristocera_sp1_EX552" 
wwnms "Phaeogenes_sp_BS_UCE_Ich212"    "Pristocerus_sp1_EX552"
      [,9]                           [,10]                            
znms  "Rhytidoponera_chalybaea_"     "Ropronia_garmani_USMNENT0653896"
wwnms "Rhytidoponera_chalybaea_T000" "Ropronia_garmani_USNMENT0653896"
      [,11]                         
znms  "Trassedia_nsp_PSUC_FEM95969" 
wwnms "Trassedia_n_sp_PSUC_FEM95969"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Looks good; replace the names in xcarn with these:</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(xcarn)[badinds] <span class="ot">&lt;-</span> wwnms</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>carndat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">label=</span><span class="fu">names</span>(xcarn), <span class="at">carnivory=</span><span class="fu">unname</span>(xcarn))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's plot this:</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggtree</span>(tree, <span class="at">layout=</span><span class="st">'circular'</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">%&lt;+%</span> carndat</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_tippoint</span>(<span class="fu">aes</span>(<span class="at">col=</span><span class="fu">factor</span>(carnivory)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bisse_tutorial_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Carnivory is predominant, but there are a few distinct clades of peaceful non-carnivores in the mix. Which one of these is the ancestral trait? Did peaceful non-carnivory evolve three separate times, or has carnivory evolved multiple times?</p>
<p>Glancing at the tree, it looks like there might be some important differences between carnivores and non-carnivores in terms of branching rates in the tree. Notice that the group of non-carnivores at the top-left position of the tree look like a relatively new group of species. They share a common ancestor recently (at least relative to other clades throughout the tree, which tend to share a common ancestor in the more distant past, closer to the root of the tree). On the other hand, the group of non-carnivores close to the 3 o’clock position in the tree have pretty long terminal branch lengths, with their common ancestor a long time ago. Hmm…</p>
<p>It isn’t super clear what relationship, if any, exists between carnivory status and speciation rates – but we might be interested to know if there is one. (This is what the original authors were interested in.) On the other hand, even if a relationship between diversification and carnivory status isn’t our main focus, it still might be important for us to account for such a relationship between these things in order to obtain a reliable estimate of trait evolution in these animals (i.e.&nbsp;to color in ancestral nodes in a reasonable way). Depending on how personally invested we are in the relationship between trait and diversification, we might be inclined to think of the diversification process as being a <a href="https://en.wikipedia.org/wiki/Nuisance_parameter">nuisance parameter</a> as far as the sequence of trait changes is concerned.</p>
</section>
<section id="warm-up-ace-andor-fitmk" class="level2">
<h2 class="anchored" data-anchor-id="warm-up-ace-andor-fitmk">Warm-up: ace and/or fitMk</h2>
<p>As a warm-up, let’s start by fitting our basic Markov models from yesterday. These do not account for any relationship between trait type and branching rate whatsoever. Let’s use both ace and fitMk to see if they give similar answers:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit using ace:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>fit.er.ace <span class="ot">&lt;-</span> <span class="fu">ace</span>(xcarn, tree, <span class="at">type=</span><span class="st">'discrete'</span>, <span class="at">model=</span><span class="st">'ER'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in ace(xcarn, tree, type = "discrete", model = "ER"): model fit
suspicious: gradients apparently non-finite</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fit.ard.ace <span class="ot">&lt;-</span> <span class="fu">ace</span>(xcarn, tree, <span class="at">type=</span><span class="st">'discrete'</span>, <span class="at">model=</span><span class="st">'ARD'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in ace(xcarn, tree, type = "discrete", model = "ARD"): model fit
suspicious: gradients apparently non-finite</code></pre>
</div>
</div>
<p>We see that ace is returning errors about being unable to calculate gradients. This might be because of the long branches in our tree: over really long intervals of time, the probability of a state change in a Markov model will just be given by the stationary distribution, which depends on the relative magnitude of the different rates, but not their absolute values. If the data only contain information about the stationary distribution, there may not be sufficient information to tell us about the absolute magnitudes of the various rates. This, at least, is one potential explanation.</p>
<p>Let’s see how we do with fitMk:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit using fitMk:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>fit.er.mk <span class="ot">&lt;-</span> <span class="fu">fitMk</span>(tree, xcarn, <span class="at">model=</span><span class="st">'ER'</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>fit.ard.mk <span class="ot">&lt;-</span> <span class="fu">fitMk</span>(tree, xcarn, <span class="at">model=</span><span class="st">'ARD'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Apparently there are no errors. Hmm…</p>
<p>Let’s examine the rates in the different models, starting with the equal-rates (ER) model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fit.er.ace<span class="sc">$</span>rates</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.340472e-05</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fit.er.mk<span class="sc">$</span>rates</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.340472e-05</code></pre>
</div>
</div>
<p>In the ER model, we see that the estimates from ace and fitMk are indistinguishable. Great! How about the all rates different (ARD) model?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fit.ard.ace<span class="sc">$</span>rates</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.674517e-05 3.971149e-04</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fit.ard.mk<span class="sc">$</span>rates</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.674554e-05 3.971135e-04</code></pre>
</div>
</div>
<p>The estimates from ace and fitMk look identical in this case, too. It looks like one of the rates is almost an order of magnitude larger than the other.</p>
<section id="review-question-in-the-ard-models-which-rate-corresponds-to-a-change-from-carnivory1-to-carnivory0-and-vice-versa" class="level4">
<h4 class="anchored" data-anchor-id="review-question-in-the-ard-models-which-rate-corresponds-to-a-change-from-carnivory1-to-carnivory0-and-vice-versa">Review question: in the ARD models, which rate corresponds to a change from carnivory=1 to carnivory=0, and vice versa?</h4>
</section>
</section>
<section id="bisse-models" class="level2">
<h2 class="anchored" data-anchor-id="bisse-models">BiSSE models</h2>
<p>Now, let’s try estimating these rates using a BiSSE model. We start by specifying a likelihood function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>bisse_likelihood_carn <span class="ot">&lt;-</span> <span class="fu">make.bisse</span>(tree, xcarn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s examine this object:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>bisse_likelihood_carn</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BiSSE likelihood function:
  * Parameter vector takes 6 elements:
     - lambda0, lambda1, mu0, mu1, q01, q10
  * Function takes arguments (with defaults)
     - pars: Parameter vector
     - condition.surv [TRUE]: Condition likelihood on survial?
     - root [ROOT.OBS]: Type of root treatment
     - root.p [NULL]: Vector of root state probabilities
     - intermediates [FALSE]: Also return intermediate values?
  * Phylogeny with 765 tips and 764 nodes
     - Taxa: Chrysolampus_sp_ANIC00035_0189, ...
  * References:
     - Maddison et al. (2007) doi:10.1080/10635150701607033
     - FitzJohn et al. (2009) doi:10.1093/sysbio/syp067
R definition:
function (pars, condition.surv = TRUE, root = ROOT.OBS, root.p = NULL, 
    intermediates = FALSE)  </code></pre>
</div>
</div>
<p>The most important bit of information for us is the first section that explains the parameters this model accepts: two diversification/speciation rates (lambda0 and lambda1), two death/extinction rates (mu0 and mu1), and finally our rates of change in trait type over time (q01 and q10).</p>
<p>The observant among you will notice that this list includes six (6) parameters. Our ARD models previously had 2. Tripling the number of parameters is a pretty big change. Is there any way we can start with a simpler case and gradually make the model more complex? After all, I don’t have the faintest idea what values of lambda and mu make sense for these data. Also, what if I want to consider an ER model?</p>
</section>
</section>
<section id="er-model-in-bisse" class="level1">
<h1>ER model in BiSSE</h1>
<p>There is a very convenient way to impose restrictions on the parameters to make the model simpler in diversitree. As a baseline, let’s see what happens if we use an ER model, and assume that diversification/extinction are independent of the trait. In this case, I expect to get similar results to ace/fitMk in the ER case. To create this model, we do the following:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bisse_likelihood_er_indep <span class="ot">&lt;-</span> <span class="fu">constrain</span>(bisse_likelihood_carn, <span class="at">formulae=</span><span class="fu">c</span>(lambda0<span class="sc">~</span>lambda1, mu0<span class="sc">~</span>mu1, q10<span class="sc">~</span>q01))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>bisse_likelihood_er_indep</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BiSSE likelihood function:
  * Parameter vector takes 3 elements:
     - lambda1, mu1, q01
  * Function constrained (original took 6 elements):
     - lambda0 ~ lambda1
     - mu0 ~ mu1
     - q10 ~ q01
  * Function takes arguments (with defaults)
     - pars: Parameter vector
     - ...: Additional arguments to underlying function
     - pars.only [FALSE]: Return full parameter vector?
  * Phylogeny with 765 tips and 764 nodes
     - Taxa: Chrysolampus_sp_ANIC00035_0189, ...
  * References:
     - Maddison et al. (2007) doi:10.1080/10635150701607033
     - FitzJohn et al. (2009) doi:10.1093/sysbio/syp067
R definition:
function (pars, ..., pars.only = FALSE)  </code></pre>
</div>
</div>
<p>This seems a little more manageable. Let’s start by trying to estimate the parameters of this model, and use our estimates from the ace/fitMk ER model as an initial guess for q10=q01. I’m just going to try some different values to see how the likelihood is behaving:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bisse_likelihood_er_indep</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,fit.er.ace<span class="sc">$</span>rates))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -49375.97</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bisse_likelihood_er_indep</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,fit.er.ace<span class="sc">$</span>rates))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -6082.483</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bisse_likelihood_er_indep</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,fit.er.ace<span class="sc">$</span>rates))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Inf</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bisse_likelihood_er_indep</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,fit.er.ace<span class="sc">$</span>rates))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -49906.06</code></pre>
</div>
</div>
<p>We will be estimating parameters by Maximum Likelihood, so the second guess seems like the most reasonable one on this list. Let’s start the optimization from there to see what we get:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit.bisse.er.indep <span class="ot">&lt;-</span> <span class="fu">find.mle</span>(bisse_likelihood_er_indep, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,fit.er.ace<span class="sc">$</span>rates))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>fit.bisse.er.indep</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$par
     lambda1          mu1          q01 
1.545313e-02 4.612131e-09 8.213603e-05 

$lnLik
[1] -3975.768

$counts
[1] 503

$convergence
[1] 0

$message
[1] "success! tolerance satisfied"

$hessian
NULL

$method
[1] "subplex"

$par.full
     lambda0      lambda1          mu0          mu1          q01          q10 
1.545313e-02 1.545313e-02 4.612131e-09 4.612131e-09 8.213603e-05 8.213603e-05 

$func.class
[1] "constrained" "bisse"       "dtlik"       "function"   

attr(,"func")
BiSSE likelihood function:
  * Parameter vector takes 3 elements:
     - lambda1, mu1, q01
  * Function constrained (original took 6 elements):
     - lambda0 ~ lambda1
     - mu0 ~ mu1
     - q10 ~ q01
  * Function takes arguments (with defaults)
     - pars: Parameter vector
     - ...: Additional arguments to underlying function
     - pars.only [FALSE]: Return full parameter vector?
  * Phylogeny with 765 tips and 764 nodes
     - Taxa: Chrysolampus_sp_ANIC00035_0189, ...
  * References:
     - Maddison et al. (2007) doi:10.1080/10635150701607033
     - FitzJohn et al. (2009) doi:10.1093/sysbio/syp067
R definition:
function (pars, ..., pars.only = FALSE)  
attr(,"class")
[1] "fit.mle.bisse" "fit.mle"      </code></pre>
</div>
</div>
<p>It looks like we were able to fit this model without problems (the $message entry says “success! tolerance satisfied”, and the $convergence entry says “0”, which is also a good sign – problems usually produce different error codes in that entry).</p>
<p>Looking at the estimates themselves, we see that our ER model rate is <span class="math inline">\(8.21 \times 10^{-5}\)</span>, which is pretty close to the value of <span class="math inline">\(8.34 \times 10^{-5}\)</span> we had from ace and fitMk. So, they’re close… but not identical.</p>
<p>We see that the overall diversification rate is <span class="math inline">\(\lambda = 1.54 \times 10^{-2}\)</span>, the extinction rate is <span class="math inline">\(\mu = 4.61 \times 10^{-9}\)</span>.</p>
<p>At this point, there are two obvious incremental complications we could introduce. We could try fitting an ARD model while still treating diversification independent of state, or we could stick with the ER model and allow for the possibility that diversification/extinction depend on carnivory status.</p>
<p>Let’s do this second one:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>bisse_likelihood_er <span class="ot">&lt;-</span> <span class="fu">constrain</span>(bisse_likelihood_carn, <span class="at">formulae=</span><span class="fu">c</span>(q10<span class="sc">~</span>q01))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>bisse_likelihood_er</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BiSSE likelihood function:
  * Parameter vector takes 5 elements:
     - lambda0, lambda1, mu0, mu1, q01
  * Function constrained (original took 6 elements):
     - q10 ~ q01
  * Function takes arguments (with defaults)
     - pars: Parameter vector
     - ...: Additional arguments to underlying function
     - pars.only [FALSE]: Return full parameter vector?
  * Phylogeny with 765 tips and 764 nodes
     - Taxa: Chrysolampus_sp_ANIC00035_0189, ...
  * References:
     - Maddison et al. (2007) doi:10.1080/10635150701607033
     - FitzJohn et al. (2009) doi:10.1093/sysbio/syp067
R definition:
function (pars, ..., pars.only = FALSE)  </code></pre>
</div>
</div>
<p>This has five parameters to estimate, which is certainly more than three from the previous model. However, we have a good starting guess for the lambdas and the mus. Let’s use it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Place our previous estimate in a vector for convenience:</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>init <span class="ot">&lt;-</span> fit.bisse.er.indep<span class="sc">$</span>par</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>fit.bisse.er <span class="ot">&lt;-</span> <span class="fu">find.mle</span>(bisse_likelihood_er, <span class="fu">c</span>(init[<span class="dv">1</span>],init[<span class="dv">1</span>],init[<span class="dv">2</span>],init[<span class="dv">2</span>],init[<span class="dv">3</span>]) )</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>fit.bisse.er</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$par
     lambda1      lambda1          mu1          mu1          q01 
1.787200e-02 1.522435e-02 1.166234e-03 1.070834e-08 8.214490e-05 

$lnLik
[1] -3975.037

$counts
[1] 405

$convergence
[1] 0

$message
[1] "success! tolerance satisfied"

$hessian
NULL

$method
[1] "subplex"

$par.full
     lambda0      lambda1          mu0          mu1          q01          q10 
1.787200e-02 1.522435e-02 1.166234e-03 1.070834e-08 8.214490e-05 8.214490e-05 

$func.class
[1] "constrained" "bisse"       "dtlik"       "function"   

attr(,"func")
BiSSE likelihood function:
  * Parameter vector takes 5 elements:
     - lambda0, lambda1, mu0, mu1, q01
  * Function constrained (original took 6 elements):
     - q10 ~ q01
  * Function takes arguments (with defaults)
     - pars: Parameter vector
     - ...: Additional arguments to underlying function
     - pars.only [FALSE]: Return full parameter vector?
  * Phylogeny with 765 tips and 764 nodes
     - Taxa: Chrysolampus_sp_ANIC00035_0189, ...
  * References:
     - Maddison et al. (2007) doi:10.1080/10635150701607033
     - FitzJohn et al. (2009) doi:10.1093/sysbio/syp067
R definition:
function (pars, ..., pars.only = FALSE)  
attr(,"class")
[1] "fit.mle.bisse" "fit.mle"      </code></pre>
</div>
</div>
<p>From this output, we see that the optimization appeared to converge successfully. The two diversification rates (lambda0 and lambda1) are pretty close to each other, but the two extinction rates (mu0 and mu1) are very different from each other. The parameter mu0 is over five orders of magnitude larger than mu1. However, our estimate for <span class="math inline">\(q\)</span> in the ER model seems unaffected, holding steady at <span class="math inline">\(q=8.21 \times 10^{-5}\)</span>.</p>
<section id="glr-tests-in-bisse-models" class="level3">
<h3 class="anchored" data-anchor-id="glr-tests-in-bisse-models">GLR tests in BiSSE models</h3>
<p>We can ask whether the difference in extinction rates is statistically significant. The fit of our two BiSSE models is very similar in terms of log-likelihood. Previously, the log-likelihood under the assumption of no relationship between diversifiction/extinction and trait change was <span class="math inline">\(\ln \mathcal{L} = -3975.768\)</span>. In this more complicated model, with five parameters, we have <span class="math inline">\(\ln \mathcal{L} = -3975.037\)</span>. The simpler model with three parameters is nested within the more complicated model with five parameters, so we can apply a <a href="https://en.wikipedia.org/wiki/Likelihood-ratio_test">Generalized Likelihood Ratio test</a> to see if the model with the additional two parameters is supported by the data. (My guess is that it will not be – the improvement in log-likelihood is miniscule.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (<span class="sc">-</span><span class="fl">3975.037+3975.768</span>), <span class="at">df=</span><span class="dv">2</span>, <span class="at">lower=</span>F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5185727</code></pre>
</div>
</div>
<p>Remember that the test statistic is <span class="math inline">\(2 \times (-3975.037 - -3975.768)\)</span>, and under the null hypothesis that the data actually do arise from the simpler model, this quantity is <span class="math inline">\(\chi^2\)</span>-distributed with two degrees of freedom (because the more complex model has two additional parameters). The quantity we just calculated is the p-value, that is, the probability of observing a value of the test statistic as extreme or more extreme than the one we actually observed (here, “extreme” means “large”). A p-value of 0.52 is not remotely close to statistical significance. On this basis, we would say that the more complex model is not supported by the data.</p>
<p>It is probably worth pointing out that just looking at differences in parameter estimates is not a reliable way to judge whether a more complicated model is supported by the data or not. When we allowed for the possibility that diversification and extinction rates could differ by carnivory status, we saw that one of the extinction rates looked like <span class="math inline">\(10^{-3}\)</span> and the other was on the order of <span class="math inline">\(10^{-8}\)</span>. In the simpler model where the extinction rates were constrained to equal each other,we got an estimate on the order of <span class="math inline">\(10^{-9}\)</span>–<span class="math inline">\(10^{-8}\)</span>. This is a huge difference – but the likelihood, or measure of fit to the data, did not change by a meaningful amount. In general, this type of instability in parameter estimates is an indication that the data contain limited information about the parameter (in this case, extinction rates) in the first place. Take this lesson to heart.</p>
<p>For futher reading (and in case the point is not driven home strongly enough) you may find this paper interesting:</p>
<p><strong>Rabosky DL. Extinction rates should not be estimated from molecular phylogenies. Evolution. 2010 Jun;64(6):1816-24. doi: 10.1111/j.1558-5646.2009.00926.x. Epub 2009 Dec 17. PMID: 20030708.</strong></p>
<p>For the Hymenoptera carnivory data, when fitting an ER model, it seems that (i) our estimated rate of state change does not change very much when we simultaneously estimate a diversification and extinction rate, and (ii) there is not any convincing evidence of a relationship between carnivory status and diversification/extinction rates.</p>
</section>
<section id="ancestral-state-reconstructions-with-bisse" class="level2">
<h2 class="anchored" data-anchor-id="ancestral-state-reconstructions-with-bisse">Ancestral state reconstructions with BiSSE</h2>
<p><strong>What about ancestral state reconstructions?</strong> We might expect the inferences at internal nodes to be pretty similar to what we see from ace/fitMk, but we might as well verify this now. Let’s plot the most likely ancestral states at the internal nodes of our tree under ace, and compare this with our BiSSE model estimates. We will need the asr.marginal function for the BiSSE models:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>asr.bisse.er.indep <span class="ot">&lt;-</span> <span class="fu">asr.marginal</span>(bisse_likelihood_er_indep,<span class="fu">coef</span>(fit.bisse.er.indep))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>asr.bisse.er <span class="ot">&lt;-</span> <span class="fu">asr.marginal</span>(bisse_likelihood_er, <span class="fu">coef</span>(fit.bisse.er))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the bisse asr's are annoyingly transposed compared to the ace lik.anc entry</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>asr.bisse.er.indep <span class="ot">&lt;-</span> <span class="fu">t</span>(asr.bisse.er.indep)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>asr.bisse.er <span class="ot">&lt;-</span> <span class="fu">t</span>(asr.bisse.er)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>asr.ace.er <span class="ot">&lt;-</span> fit.er.ace<span class="sc">$</span>lik.anc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then we can plot these:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the estimates from ace</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree, <span class="at">show.tip.label =</span> <span class="cn">FALSE</span>, <span class="at">cex=</span><span class="fl">0.1</span>, <span class="at">type=</span><span class="st">'fan'</span>, <span class="at">main=</span><span class="st">'ace ER'</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nodelabels</span>(<span class="at">pie =</span> fit.er.ace<span class="sc">$</span>lik.anc, <span class="at">piecol =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>), <span class="at">cex =</span> <span class="fl">0.3</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tiplabels</span>(<span class="at">pie =</span> <span class="fu">cbind</span>(<span class="dv">1</span> <span class="sc">-</span> xcarn, xcarn), <span class="at">piecol =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>), <span class="at">cex =</span> <span class="fl">0.14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bisse_tutorial_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the estimates from the bisse.indep model:</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree, <span class="at">show.tip.label =</span> <span class="cn">FALSE</span>, <span class="at">cex=</span><span class="fl">0.1</span>, <span class="at">type=</span><span class="st">'fan'</span>,<span class="at">main=</span><span class="st">'BiSSE ER 3 pars'</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nodelabels</span>(<span class="at">pie =</span> asr.bisse.er.indep, <span class="at">piecol =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>), <span class="at">cex =</span> <span class="fl">0.3</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tiplabels</span>(<span class="at">pie =</span> <span class="fu">cbind</span>(<span class="dv">1</span> <span class="sc">-</span> xcarn, xcarn), <span class="at">piecol =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>), <span class="at">cex =</span> <span class="fl">0.14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bisse_tutorial_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the estimates from the bisse model that we tossed out under the GLR test:</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree, <span class="at">show.tip.label =</span> <span class="cn">FALSE</span>, <span class="at">cex=</span><span class="fl">0.1</span>, <span class="at">type=</span><span class="st">'fan'</span>,<span class="at">main=</span><span class="st">'BiSSE ER 5 pars'</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nodelabels</span>(<span class="at">pie =</span> asr.bisse.er, <span class="at">piecol =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>), <span class="at">cex =</span> <span class="fl">0.3</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tiplabels</span>(<span class="at">pie =</span> <span class="fu">cbind</span>(<span class="dv">1</span> <span class="sc">-</span> xcarn, xcarn), <span class="at">piecol =</span> <span class="fu">c</span>(<span class="st">"steelblue"</span>, <span class="st">"tomato"</span>), <span class="at">cex =</span> <span class="fl">0.14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bisse_tutorial_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These look indistinguishable from each other to me – which is what I expected, given the similary in the estimated rates of trait change. Accounting for diversification/extinction in the ER model does not seem to affect our ancestral state reconstructions.</p>
<p>What is the ancestral state reconstruction under the ER model, anyway? It seems that the progenitor of the extant species in <em>Hymenoptera</em> was not carnivorous. Most of the signal in the data for this is probably coming from the clade near the 3 o’clock position in the tree consisting of very old species (relative to the rest) that are all not carnivorous.</p>
<p>We have not done character mapping, so we are not able to identify precisely when state changes occurred along branches. However, the plausible scenario seems to be that the common ancestor for all of the species was not carnivorous, but carnivory evolved in one lineage a very long time ago. Since then, non-carnivory has independently evolved twice.</p>
<p><strong>Do you think the answer will change if we consider asymmetric trait change, i.e.&nbsp;an ARD model?</strong></p>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
</section>
</section>
<section id="section" class="level1">
<h1>1.</h1>
<p>We never actually asked whether the ARD model was statistically supported over the ER model when we were using ace. Carry out a Generalized Likelihood Ratio Test to determine whether differences in <span class="math inline">\(q_{01}\)</span> and <span class="math inline">\(q_{10}\)</span> are statistically significant when using ace (or fitMk).</p>
</section>
<section id="section-1" class="level1">
<h1>2.</h1>
<p>Fit an ARD model for the carnivory data under the assumption that the diversification and extinction rates are independent of the trait. Use the <code>constrain</code> function to help you. You may find it useful to start the optimization from ace’s ARD estimates (and feel free to use the BiSSE ER model’s diversification/extinction rate estimates as well).</p>
</section>
<section id="section-2" class="level1">
<h1>3.</h1>
<p>Next, fit your ARD model under the assumption that diversification and extinction rates can differ by trait. Does a Generalized Likelihood Ratio Test indicate that speciation/extinction rates differ by carnivory status?</p>
</section>
<section id="section-3" class="level1">
<h1>4.</h1>
<p>What happens if you compare this full BiSSE model with the simplest possible case (ER model with diversification/extinction uncorrelated with carnivory status) under a Generalized Likelihood Ratio Test?</p>
</section>
<section id="section-4" class="level1">
<h1>5.</h1>
<p>Load in a different Hymenoptera dataset of your choice. Do you find evidence of correlation between trait and diversification/extinction rates? How does this affect your estimates of ancestral states? Repeat the workflow of the tutorial and questions 1-4 to arrive at an answer.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("example\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>