# Final exercises

For the rest of the afternoon (or until we want to go home), we will explore the following analyses: 

## 1. 
We have a posterior collection of Influenza H5N1 trees that we obtained in BEAST2. These trees are not character-mapped with location. We should try running ace/simmap/SSE/SAASI/whatever to see how our estimates of ancestral locations do or do not agree across these models. 


## 2.
We have a second posterior collection of trees that used geographic information to jointly estimate migration rates with the phylogeny. Let's compare these to the answers we get from Step 1.

## 3. 
We have a third posterior collection that is similar to the one from Step 2, except that we activated BSSVS to constrain a simpler migration model. Let's see if we can adapt our analysis from Step 1 to incorporate LASSO or some other form of regularization on the models in ace/fitMk/etc. to determine if that is a viable alternative to the full BSSVS approach.

## Comparing tree topologies
Part of the rationale for joint estimation is to accommodate phylogenetic uncertainty in our ancestral state estimates. However, a two-step approach (using, e.g. the posterior collection from Step 1) should address this already. Do we gain anything by jointly estimating complicated models of geographic movement with our phylogeny? How does our phylogenetic reconstruction change if we include geographic information?



 

